#ifndef GC_COLLECTION_KIND_H
#define GC_COLLECTION_KIND_H

enum gc_collection_kind {
  GC_COLLECTION_ANY,
  GC_COLLECTION_MINOR,
  GC_COLLECTION_MAJOR,
  GC_COLLECTION_COMPACTING,
};

#endif // GC_COLLECTION_KIND_H
